name = "StructuredStaticCondensation"
uuid = "15b68823-0350-4e39-8f77-296b000e3fd2"
authors = ["James Cook <cookjws@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
